[itsi_maintenance_window]
python.version = python3
is_custom = 1
label = ITSI Maintenance Window
description = Create ITSI maintenance windows for CMDB CIs in operation_status=maintenance
icon_path = appIcon.png
payload_format = json
param.title_prefix = CMDB Maintenance
param.identifier_field = title
param.object_type = entity
