[install]
is_configured = 0
state = enabled

[ui]
is_visible = 1
label = ITSI Maintenance Window Alert

[launcher]
author = Rob Gustafson
description = Custom alert action that creates ITSI maintenance windows from CMDB rows with operation_status=maintenance
version = 0.1.0

[package]
id = TA-itsi-maintenance-window

[id]
name = TA-itsi-maintenance-window
version = 0.1.0
